ban-command: "litebans:ban {player} 3days {reason}"
vote-up-player-percent: 0.5
vote-timed-out: 60000 # 1min
lang:
  player-is-invalid: "§c玩家不在线或是不存在"
  broadcast: "§b玩家 {player} 正被风纪委员系统以 {reason} 的理由投票封禁，输入/ju vote {player} 以投票封禁玩家"
  ban-success: "§c玩家 {player} 已被风纪委员系统封禁"
  vote-success: "§a投票成功!当前投票数 {current}/{max}"
  player-is-not-being-voted: "§c目标玩家未被正在投票封禁"
  player-is-already-being-voted: "§c目标玩家已经正在被投票封禁"
  already-voted: "§c您已经投过票了"